"""Add feature-gating, auto-notifications, and analytics tables

Revision ID: 0af50fc76025
Revises: 0ebf11d8390d
Create Date: 2026-03-22 21:10:26.154842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0af50fc76025'
down_revision: Union[str, Sequence[str], None] = '0ebf11d8390d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = inspect(op.get_bind())
    # Fresh environments can start from init_schema baseline where these tables already exist.
    if inspector.has_table('plan_feature') and inspector.has_table('notificacion_automatica'):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_feature',
    sa.Column('plan_feature_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.Enum('AUTO_REMINDERS', 'AUTO_CONFIRMACION', 'AUTO_RECOVERY', 'AUTO_RESEÑA_PROMPT', 'DESTACADO_LISTING', 'CAMPAÑAS_VISIBILIDAD', 'ANALYTICS_OCUPACION', 'ANALYTICS_CLIENTES', 'SUGERIR_PROMOS', 'NOTIF_SMS', 'NOTIF_EMAIL', 'REPORTES_AVANZADOS', name='featurekey', native_enum=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plan_feature_id')
    )
    op.create_table('analytics_ocupacion',
    sa.Column('analytics_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweek', native_enum=False), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('capacidad_total', sa.Integer(), nullable=True),
    sa.Column('citas_confirmadas', sa.Integer(), nullable=True),
    sa.Column('citas_completadas', sa.Integer(), nullable=True),
    sa.Column('citas_canceladas', sa.Integer(), nullable=True),
    sa.Column('citas_pendientes', sa.Integer(), nullable=True),
    sa.Column('tasa_ocupacion', sa.Float(), nullable=True),
    sa.Column('tasa_no_show', sa.Float(), nullable=True),
    sa.Column('tasa_cancelacion', sa.Float(), nullable=True),
    sa.Column('ingresos_estimados', sa.Float(), nullable=True),
    sa.Column('calculado_en', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    op.create_table('sugerencia_promocion',
    sa.Column('sugerencia_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('tasa_ocupacion', sa.Float(), nullable=True),
    sa.Column('descuento_sugerido', sa.Float(), nullable=True),
    sa.Column('visto', sa.Boolean(), nullable=True),
    sa.Column('implementado', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sugerencia_id')
    )
    op.create_table('trabajador',
    sa.Column('trabajador_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trabajador_id')
    )
    op.create_table('notificacion_automatica',
    sa.Column('notif_auto_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('establecimiento_id', sa.Integer(), nullable=True),
    sa.Column('mensaje_id', sa.Integer(), nullable=True),
    sa.Column('pago_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('APPOINTMENT_REMINDER', 'APPOINTMENT_CONFIRMATION', 'APPOINTMENT_COMPLETION', 'APPOINTMENT_CANCELLATION', 'MESSAGE_RECEIVED', 'PAYMENT_FAILED', 'REVIEW_REQUEST', 'RECOVERY_OFFER', name='autonotificationtype', native_enum=False), nullable=False),
    sa.Column('canal', sa.Enum('IN_APP', 'PUSH', 'EMAIL', 'SMS', name='notificationchannel', native_enum=False), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('url_accion', sa.String(length=500), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('fecha_enviada', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('PENDING', 'SENT', 'FAILED', 'CANCELLED', name='autonotificationstatus', native_enum=False), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.cita_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensaje.mensaje_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.pago_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notif_auto_id')
    )
    op.alter_column('agenda', 'establecimiento_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('agenda', 'dia_semana',
               existing_type=mysql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweek', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('idx_dia'), table_name='agenda')
    op.drop_index(op.f('idx_establecimiento'), table_name='agenda')
    op.alter_column('cita', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('cita', 'servicio_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('cita', 'estado',
               existing_type=mysql.ENUM('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='appointmentstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.drop_index(op.f('idx_cliente'), table_name='cita')
    op.drop_index(op.f('idx_estado'), table_name='cita')
    op.drop_index(op.f('idx_fecha'), table_name='cita')
    op.drop_index(op.f('idx_fecha_hora'), table_name='cita')
    op.drop_index(op.f('idx_servicio'), table_name='cita')
    op.drop_column('cita', 'fecha_modificacion')
    op.drop_index(op.f('idx_activo'), table_name='establecimiento')
    op.drop_index(op.f('idx_ubicacion'), table_name='establecimiento')
    op.drop_index(op.f('idx_usuario'), table_name='establecimiento')
    op.drop_column('establecimiento', 'fecha_creacion')
    op.drop_index(op.f('idx_cita'), table_name='mensaje')
    op.drop_index(op.f('idx_emisor'), table_name='mensaje')
    op.drop_index(op.f('idx_fecha'), table_name='mensaje')
    op.add_column('notificacion', sa.Column('leida', sa.Boolean(), nullable=True))
    op.alter_column('notificacion', 'tipo',
               existing_type=mysql.ENUM('INFO', 'ALERTA', 'RECORDATORIO', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('INFO', 'ALERTA', 'RECORDATORIO', name='notificationtype', native_enum=False),
               existing_nullable=False)
    op.drop_index(op.f('idx_fecha'), table_name='notificacion')
    op.drop_index(op.f('idx_usuario_leido'), table_name='notificacion')
    op.drop_column('notificacion', 'leido')
    op.alter_column('pago', 'metodo_pago',
               existing_type=mysql.ENUM('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', name='paymentmethod', native_enum=False),
               existing_nullable=False)
    op.alter_column('pago', 'estado',
               existing_type=mysql.ENUM('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', name='paymentstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.drop_index(op.f('idx_estado'), table_name='pago')
    op.drop_index(op.f('idx_fecha'), table_name='pago')
    op.drop_index(op.f('idx_suscripcion'), table_name='pago')
    op.drop_index(op.f('idx_transaccion'), table_name='pago')
    op.drop_column('pago', 'transaccion_id')
    op.drop_column('perfil', 'fecha_actualizacion')
    op.add_column('plan', sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_index(op.f('idx_activo'), table_name='plan')
    op.drop_column('plan', 'max_servicios')
    op.drop_column('plan', 'precio_mensual')
    op.drop_column('plan', 'max_citas_mes')
    op.add_column('reporte', sa.Column('establecimiento_id', sa.Integer(), nullable=False))
    op.add_column('reporte', sa.Column('fecha_generacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('idx_estado'), table_name='reporte')
    op.drop_index(op.f('idx_tipo'), table_name='reporte')
    op.drop_index(op.f('idx_usuario'), table_name='reporte')
    op.drop_constraint(op.f('reporte_ibfk_1'), 'reporte', type_='foreignkey')
    op.create_foreign_key(None, 'reporte', 'establecimiento', ['establecimiento_id'], ['establecimiento_id'], ondelete='CASCADE')
    op.drop_column('reporte', 'tipo')
    op.drop_column('reporte', 'estado')
    op.drop_column('reporte', 'fecha_resolucion')
    op.drop_column('reporte', 'usuario_id')
    op.drop_column('reporte', 'entidad_id')
    op.drop_column('reporte', 'fecha_creacion')
    op.add_column('resena', sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('resena', 'establecimiento_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('resena', 'usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('resena', 'calificacion',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_calificacion'), table_name='resena')
    op.drop_index(op.f('idx_establecimiento'), table_name='resena')
    op.drop_index(op.f('idx_usuario'), table_name='resena')
    op.drop_index(op.f('unique_usuario_establecimiento'), table_name='resena')
    op.create_unique_constraint('unique_usuario_establecimiento_review', 'resena', ['usuario_id', 'establecimiento_id'])
    op.drop_column('resena', 'fecha_creacion')
    op.alter_column('rol', 'descripcion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_activo'), table_name='servicio')
    op.drop_index(op.f('idx_establecimiento'), table_name='servicio')
    op.drop_column('servicio', 'fecha_creacion')
    op.alter_column('suscripcion', 'estado',
               existing_type=mysql.ENUM('ACTIVA', 'CANCELADA', 'EXPIRADA', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('ACTIVA', 'CANCELADA', 'EXPIRADA', name='subscriptionstatus', native_enum=False),
               existing_nullable=True,
               existing_server_default=sa.text("'ACTIVA'"))
    op.drop_index(op.f('idx_establecimiento'), table_name='suscripcion')
    op.drop_index(op.f('idx_estado'), table_name='suscripcion')
    op.drop_index(op.f('idx_fecha_fin'), table_name='suscripcion')
    op.drop_index(op.f('idx_plan'), table_name='suscripcion')
    op.drop_column('suscripcion', 'auto_renovacion')
    op.drop_index(op.f('idx_activo'), table_name='usuario')
    op.drop_index(op.f('idx_correo'), table_name='usuario')
    op.drop_index(op.f('idx_rol'), table_name='usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_rol'), 'usuario', ['rol_id'], unique=False)
    op.create_index(op.f('idx_correo'), 'usuario', ['correo'], unique=False)
    op.create_index(op.f('idx_activo'), 'usuario', ['activo'], unique=False)
    op.add_column('suscripcion', sa.Column('auto_renovacion', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_plan'), 'suscripcion', ['plan_id'], unique=False)
    op.create_index(op.f('idx_fecha_fin'), 'suscripcion', ['fecha_fin'], unique=False)
    op.create_index(op.f('idx_estado'), 'suscripcion', ['estado'], unique=False)
    op.create_index(op.f('idx_establecimiento'), 'suscripcion', ['establecimiento_id'], unique=False)
    op.alter_column('suscripcion', 'estado',
               existing_type=sa.Enum('ACTIVA', 'CANCELADA', 'EXPIRADA', name='subscriptionstatus', native_enum=False),
               type_=mysql.ENUM('ACTIVA', 'CANCELADA', 'EXPIRADA', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'ACTIVA'"))
    op.add_column('servicio', sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.create_index(op.f('idx_establecimiento'), 'servicio', ['establecimiento_id'], unique=False)
    op.create_index(op.f('idx_activo'), 'servicio', ['activo'], unique=False)
    op.alter_column('rol', 'descripcion',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.add_column('resena', sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_constraint('unique_usuario_establecimiento_review', 'resena', type_='unique')
    op.create_index(op.f('unique_usuario_establecimiento'), 'resena', ['usuario_id', 'establecimiento_id'], unique=True)
    op.create_index(op.f('idx_usuario'), 'resena', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_establecimiento'), 'resena', ['establecimiento_id'], unique=False)
    op.create_index(op.f('idx_calificacion'), 'resena', ['calificacion'], unique=False)
    op.alter_column('resena', 'calificacion',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('resena', 'usuario_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('resena', 'establecimiento_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('resena', 'fecha')
    op.add_column('reporte', sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('reporte', sa.Column('entidad_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('reporte', sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reporte', sa.Column('fecha_resolucion', mysql.TIMESTAMP(), nullable=True))
    op.add_column('reporte', sa.Column('estado', mysql.ENUM('PENDIENTE', 'EN_REVISION', 'RESUELTO', 'RECHAZADO', collation='utf8mb4_unicode_ci'), server_default=sa.text("'PENDIENTE'"), nullable=True))
    op.add_column('reporte', sa.Column('tipo', mysql.ENUM('USUARIO', 'ESTABLECIMIENTO', 'SERVICIO', 'CITA', collation='utf8mb4_unicode_ci'), nullable=False))
    op.drop_constraint(None, 'reporte', type_='foreignkey')
    op.create_foreign_key(op.f('reporte_ibfk_1'), 'reporte', 'usuario', ['usuario_id'], ['usuario_id'], ondelete='SET NULL')
    op.create_index(op.f('idx_usuario'), 'reporte', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_tipo'), 'reporte', ['tipo'], unique=False)
    op.create_index(op.f('idx_estado'), 'reporte', ['estado'], unique=False)
    op.drop_column('reporte', 'fecha_generacion')
    op.drop_column('reporte', 'establecimiento_id')
    op.add_column('plan', sa.Column('max_citas_mes', mysql.INTEGER(), server_default=sa.text("'100'"), autoincrement=False, nullable=True))
    op.add_column('plan', sa.Column('precio_mensual', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('plan', sa.Column('max_servicios', mysql.INTEGER(), server_default=sa.text("'10'"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_activo'), 'plan', ['activo'], unique=False)
    op.drop_column('plan', 'precio')
    op.add_column('perfil', sa.Column('fecha_actualizacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('pago', sa.Column('transaccion_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.create_index(op.f('idx_transaccion'), 'pago', ['transaccion_id'], unique=False)
    op.create_index(op.f('idx_suscripcion'), 'pago', ['suscripcion_id'], unique=False)
    op.create_index(op.f('idx_fecha'), 'pago', ['fecha_pago'], unique=False)
    op.create_index(op.f('idx_estado'), 'pago', ['estado'], unique=False)
    op.alter_column('pago', 'estado',
               existing_type=sa.Enum('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', name='paymentstatus', native_enum=False),
               type_=mysql.ENUM('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.alter_column('pago', 'metodo_pago',
               existing_type=sa.Enum('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', name='paymentmethod', native_enum=False),
               type_=mysql.ENUM('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.add_column('notificacion', sa.Column('leido', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_usuario_leido'), 'notificacion', ['usuario_id', 'leido'], unique=False)
    op.create_index(op.f('idx_fecha'), 'notificacion', ['fecha_envio'], unique=False)
    op.alter_column('notificacion', 'tipo',
               existing_type=sa.Enum('INFO', 'ALERTA', 'RECORDATORIO', name='notificationtype', native_enum=False),
               type_=mysql.ENUM('INFO', 'ALERTA', 'RECORDATORIO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_column('notificacion', 'leida')
    op.create_index(op.f('idx_fecha'), 'mensaje', ['fecha_envio'], unique=False)
    op.create_index(op.f('idx_emisor'), 'mensaje', ['emisor_id'], unique=False)
    op.create_index(op.f('idx_cita'), 'mensaje', ['cita_id'], unique=False)
    op.add_column('establecimiento', sa.Column('fecha_creacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.create_index(op.f('idx_usuario'), 'establecimiento', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_ubicacion'), 'establecimiento', ['latitud', 'longitud'], unique=False)
    op.create_index(op.f('idx_activo'), 'establecimiento', ['activo'], unique=False)
    op.add_column('cita', sa.Column('fecha_modificacion', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.create_index(op.f('idx_servicio'), 'cita', ['servicio_id'], unique=False)
    op.create_index(op.f('idx_fecha_hora'), 'cita', ['fecha', 'hora_inicio'], unique=False)
    op.create_index(op.f('idx_fecha'), 'cita', ['fecha'], unique=False)
    op.create_index(op.f('idx_estado'), 'cita', ['estado'], unique=False)
    op.create_index(op.f('idx_cliente'), 'cita', ['cliente_id'], unique=False)
    op.alter_column('cita', 'estado',
               existing_type=sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='appointmentstatus', native_enum=False),
               type_=mysql.ENUM('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', collation='utf8mb4_unicode_ci'),
               existing_nullable=True,
               existing_server_default=sa.text("'PENDIENTE'"))
    op.alter_column('cita', 'servicio_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('cita', 'cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('idx_establecimiento'), 'agenda', ['establecimiento_id'], unique=False)
    op.create_index(op.f('idx_dia'), 'agenda', ['dia_semana'], unique=False)
    op.alter_column('agenda', 'dia_semana',
               existing_type=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweek', native_enum=False),
               type_=mysql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('agenda', 'establecimiento_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('notificacion_automatica')
    op.drop_table('trabajador')
    op.drop_table('sugerencia_promocion')
    op.drop_table('analytics_ocupacion')
    op.drop_table('plan_feature')
    # ### end Alembic commands ###
