"""add_unique_constraint_review

Revision ID: 4f0cbb1c32d8
Revises: c27ce2d75547
Create Date: 2026-01-31 11:56:03.248084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f0cbb1c32d8'
down_revision: Union[str, Sequence[str], None] = 'c27ce2d75547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agenda', 'dia_semana',
               existing_type=mysql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO'),
               type_=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweek', native_enum=False),
               existing_nullable=False)
    op.alter_column('cita', 'estado',
               existing_type=mysql.ENUM('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA'),
               type_=sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='appointmentstatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('notificacion', 'tipo',
               existing_type=mysql.ENUM('INFO', 'ALERTA', 'RECORDATORIO'),
               type_=sa.Enum('INFO', 'ALERTA', 'RECORDATORIO', name='notificationtype', native_enum=False),
               existing_nullable=False)
    op.alter_column('pago', 'metodo_pago',
               existing_type=mysql.ENUM('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA'),
               type_=sa.Enum('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', name='paymentmethod', native_enum=False),
               existing_nullable=False)
    op.alter_column('pago', 'estado',
               existing_type=mysql.ENUM('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO'),
               type_=sa.Enum('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', name='paymentstatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('plan', 'precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('resena', 'calificacion',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_usuario_establecimiento_review', 'resena', ['usuario_id', 'establecimiento_id'])
    op.alter_column('suscripcion', 'estado',
               existing_type=mysql.ENUM('ACTIVA', 'CANCELADA', 'EXPIRADA'),
               type_=sa.Enum('ACTIVA', 'CANCELADA', 'EXPIRADA', name='subscriptionstatus', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suscripcion', 'estado',
               existing_type=sa.Enum('ACTIVA', 'CANCELADA', 'EXPIRADA', name='subscriptionstatus', native_enum=False),
               type_=mysql.ENUM('ACTIVA', 'CANCELADA', 'EXPIRADA'),
               existing_nullable=True)
    op.drop_constraint('unique_usuario_establecimiento_review', 'resena', type_='unique')
    op.alter_column('resena', 'calificacion',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('plan', 'precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('pago', 'estado',
               existing_type=sa.Enum('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', name='paymentstatus', native_enum=False),
               type_=mysql.ENUM('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO'),
               existing_nullable=True)
    op.alter_column('pago', 'metodo_pago',
               existing_type=sa.Enum('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', name='paymentmethod', native_enum=False),
               type_=mysql.ENUM('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA'),
               existing_nullable=False)
    op.alter_column('notificacion', 'tipo',
               existing_type=sa.Enum('INFO', 'ALERTA', 'RECORDATORIO', name='notificationtype', native_enum=False),
               type_=mysql.ENUM('INFO', 'ALERTA', 'RECORDATORIO'),
               existing_nullable=False)
    op.alter_column('cita', 'estado',
               existing_type=sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='appointmentstatus', native_enum=False),
               type_=mysql.ENUM('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA'),
               existing_nullable=True)
    op.alter_column('agenda', 'dia_semana',
               existing_type=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweek', native_enum=False),
               type_=mysql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO'),
               existing_nullable=False)
    # ### end Alembic commands ###
