"""Initial migration

Revision ID: de5f83dad82e
Revises: 
Create Date: 2026-02-03 15:18:28.484905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de5f83dad82e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('rol',
    sa.Column('rol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('establecimiento',
    sa.Column('establecimiento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitud', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('establecimiento_id')
    )
    op.create_table('notificacion',
    sa.Column('notificacion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('INFO', 'ALERTA', 'RECORDATORIO', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id')
    )
    op.create_table('agenda',
    sa.Column('agenda_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweek', native_enum=False), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agenda_id'),
    sa.UniqueConstraint('establecimiento_id', 'dia_semana', name='unique_establecimiento_dia')
    )
    op.create_table('perfil',
    sa.Column('perfil_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_publica', sa.Text(), nullable=True),
    sa.Column('imagen_logo', sa.String(length=255), nullable=True),
    sa.Column('imagen_portada', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perfil_id'),
    sa.UniqueConstraint('establecimiento_id')
    )
    op.create_table('reporte',
    sa.Column('reporte_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_generacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reporte_id')
    )
    op.create_table('resena',
    sa.Column('resena_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='check_calificacion_range'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resena_id'),
    sa.UniqueConstraint('usuario_id', 'establecimiento_id', name='unique_usuario_establecimiento_review')
    )
    op.create_table('servicio',
    sa.Column('servicio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('servicio_id')
    )
    op.create_table('suscripcion',
    sa.Column('suscripcion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'CANCELADA', 'EXPIRADA', name='subscriptionstatus', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('suscripcion_id')
    )
    op.create_table('cita',
    sa.Column('cita_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='appointmentstatus', native_enum=False), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.usuario_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.servicio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cita_id')
    )
    op.create_table('pago',
    sa.Column('pago_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suscripcion_id', sa.Integer(), nullable=True),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('fecha_pago', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Enum('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', name='paymentstatus', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripcion.suscripcion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pago_id')
    )
    op.create_table('mensaje',
    sa.Column('mensaje_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.cita_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mensaje_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensaje')
    op.drop_table('pago')
    op.drop_table('cita')
    op.drop_table('suscripcion')
    op.drop_table('servicio')
    op.drop_table('resena')
    op.drop_table('reporte')
    op.drop_table('perfil')
    op.drop_table('agenda')
    op.drop_table('notificacion')
    op.drop_table('establecimiento')
    op.drop_table('usuario')
    op.drop_table('rol')
    op.drop_table('plan')
    # ### end Alembic commands ###
