"""Initial migration 2

Revision ID: e7257f7051b1
Revises: 93c7e7a93723
Create Date: 2026-01-21 13:47:54.163547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e7257f7051b1'
down_revision: Union[str, Sequence[str], None] = '93c7e7a93723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Plan',
    sa.Column('plan_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_mensual', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('max_servicios', sa.Integer(), nullable=True),
    sa.Column('max_trabajadores', sa.Integer(), nullable=True),
    sa.Column('max_citas_mes', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Rol',
    sa.Column('rol_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Usuario',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['Rol.rol_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('Establecimiento',
    sa.Column('establecimiento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitud', mysql.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('establecimiento_id')
    )
    op.create_table('Notificacion',
    sa.Column('notificacion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('INFO', 'ALERTA', 'RECORDATORIO', name='notificationtype'), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notificacion_id')
    )
    op.create_table('Reporte',
    sa.Column('reporte_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('USUARIO', 'ESTABLECIMIENTO', 'SERVICIO', 'CITA', 'TRABAJADOR', name='reporttype'), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_REVISION', 'RESUELTO', 'RECHAZADO', name='reportstatus'), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_resolucion', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('reporte_id')
    )
    op.create_table('Perfil',
    sa.Column('perfil_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=True),
    sa.Column('descripcion_publica', sa.Text(), nullable=True),
    sa.Column('imagen_logo', sa.String(length=255), nullable=True),
    sa.Column('imagen_portada', sa.String(length=255), nullable=True),
    sa.Column('fecha_actualizacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['Establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('perfil_id'),
    sa.UniqueConstraint('establecimiento_id')
    )
    op.create_table('Servicio',
    sa.Column('servicio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=False),
    sa.Column('precio', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['Establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('servicio_id')
    )
    op.create_table('Suscripcion',
    sa.Column('suscripcion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'CANCELADA', 'EXPIRADA', name='subscriptionstatus'), nullable=True),
    sa.Column('auto_renovacion', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['Establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['Plan.plan_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('suscripcion_id')
    )
    op.create_table('Trabajador',
    sa.Column('trabajador_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establecimiento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_contratacion', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['Establecimiento.establecimiento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trabajador_id')
    )
    op.create_table('Agenda',
    sa.Column('agenda_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='dayofweek'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['Trabajador.trabajador_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agenda_id'),
    sa.UniqueConstraint('trabajador_id', 'dia_semana', name='unique_trabajador_dia')
    )
    op.create_table('BloqueoAgenda',
    sa.Column('bloqueo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['Trabajador.trabajador_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bloqueo_id')
    )
    op.create_table('Cita',
    sa.Column('cita_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA', name='appointmentstatus'), nullable=True),
    sa.Column('notas_cliente', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servicio_id'], ['Servicio.servicio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['Trabajador.trabajador_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cita_id')
    )
    op.create_table('Pago',
    sa.Column('pago_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('suscripcion_id', sa.Integer(), nullable=True),
    sa.Column('monto', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('TARJETA_CREDITO', 'PAYPAL', 'TRANSFERENCIA_BANCARIA', name='paymentmethod'), nullable=False),
    sa.Column('transaccion_id', sa.String(length=255), nullable=True),
    sa.Column('fecha_pago', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.Enum('COMPLETADO', 'PENDIENTE', 'FALLIDO', 'REEMBOLSADO', name='paymentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['Suscripcion.suscripcion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pago_id')
    )
    op.create_table('TrabajadorServicio',
    sa.Column('trabajador_servicio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['servicio_id'], ['Servicio.servicio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['Trabajador.trabajador_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trabajador_servicio_id'),
    sa.UniqueConstraint('trabajador_id', 'servicio_id', name='unique_trabajador_servicio')
    )
    op.create_table('Mensaje',
    sa.Column('mensaje_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('emisor_id', sa.Integer(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['Cita.cita_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emisor_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mensaje_id')
    )
    op.create_table('Resena',
    sa.Column('resena_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='check_calificacion_range'),
    sa.ForeignKeyConstraint(['cita_id'], ['Cita.cita_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['Trabajador.trabajador_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resena_id'),
    sa.UniqueConstraint('cita_id', 'usuario_id', name='unique_cita_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resena')
    op.drop_table('Mensaje')
    op.drop_table('TrabajadorServicio')
    op.drop_table('Pago')
    op.drop_table('Cita')
    op.drop_table('BloqueoAgenda')
    op.drop_table('Agenda')
    op.drop_table('Trabajador')
    op.drop_table('Suscripcion')
    op.drop_table('Servicio')
    op.drop_table('Perfil')
    op.drop_table('Reporte')
    op.drop_table('Notificacion')
    op.drop_table('Establecimiento')
    op.drop_table('Usuario')
    op.drop_table('Rol')
    op.drop_table('Plan')
    # ### end Alembic commands ###
